DEFAULT_VOICE = "vi-VN-HoaiMyNeural"
DEFAULT_RATE = "+0%"
DEFAULT_PITCH = "+0Hz"
DEFAULT_VOLUME = "+0%"
DEFAULT_RETRIES = 3
DEFAULT_TIMEOUT = 60.0


__all__ = [
	"DEFAULT_PITCH", "DEFAULT_RATE", "DEFAULT_RETRIES", "DEFAULT_TIMEOUT",
	"DEFAULT_VOICE", "DEFAULT_VOLUME",
]
